// <auto-generated />
namespace AppTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mm3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mm3));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041100431_mm3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
